### PR TITLE
Feature: add maxRows for #275

### PR DESCRIPTION
**Pull request by cbrittingham**
Link to feature description: https://github.com/C2FO/fast-csv/issues/275

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/c2fo/fast-csv/pulls) for the same update/change?

### New Feature Submissions:

1. [ ] Have you added tests for the new feature
-> I looked at this briefly, but was not successful in finding how to unit test this properly.
2. [x] Does your submission pass tests?
3. [x] Have you lint your code locally prior to submission?
4. [x] Have you updated the docs?
    * [x] If you added new parsing or formatting options have you added them to the docs?
    * [ ] If applicable have you added an example to the parsing or formatting docs?

### CODE REVIEW

**Comment by doug-martin** [comment]
Ill take a look at this in the next day or two. 

The one thing that sticks out to me is that the maxRows should probably be in the parserStream, which can bypass the parser all together, not sure how easy that would be though.

The other thing I think we should explore with this is can we short circuit the parsing once we hit the max rows emit and end event, Im not sure how well node streams would handle this though it might cause an error.

**Comment by cbrittingham** [comment]
> Ill take a look at this in the next day or two.
> 
> The one thing that sticks out to me is that the maxRows should probably be in the parserStream, which can bypass the parser all together, not sure how easy that would be though.
> 
> The other thing I think we should explore with this is can we short circuit the parsing once we hit the max rows emit and end event, Im not sure how well node streams would handle this though it might cause an error.

Do you have any suggestions on how I could short circuit to keep from reading the entire file without an enhancement? Is there anything I could do in my first "on data" callback?

**Comment by jgchristopher** [comment]
Can we push this out as is and add a new ticket to add the short circuit functionality?

**Comment by doug-martin** [comment]
This will be in v3.5.1

**Pull request closed without merging**
