### PR TITLE
fixed issue #111 - process last cell in row if empty

### PR DESCRIPTION
**Pull request by rickwargo**
- added an empty cell to items[] when line (or file) ends with a delimiter.
- added tests in test/issues.test.js for new functionality
- added tests to test trailing delimiter in parser.test.js for each new line scenario
- (important) changed 3 tests "accept new data and return the result" to remove the trailing comma in the data. I'm not sure the test was valid the way it was written.

### CODE REVIEW

**Comment by dustinsmith1024** [comment]
I will try to review this afternoon.

**Comment by dustinsmith1024** [comment]
Looks good to me. @doug-martin or @aheuermann see any issues?

I will merge and publish tomorrow if I don't hear feedback from them.

**Comment by aheuermann** [comment]
LGTM

**Comment by dustinsmith1024** [comment]
Pushed 2.0.0 since this may be breaking change for people.  Looks like its failing on Node 6, so we will try to fix that soon.

**Pull request merged**
